
/**************************************************************
 *	
 *	bounce_sound, 8 bit, 11025Hz,
 *	1 channel, 8172 bytes/channel
 *	Total Size: 1 * 8172 + 4 (header) = 8216 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Johannes Peltop-Piri\Downloads\bounce_sound.wav
 *	Time-stamp: Tue Oct 27 10:47:58 2009
 *	
 **************************************************************/

#ifndef __BSOUNDH__
#define __BSOUNDH__

#define BOUNCE_FREQ		11025
#define BOUNCE_LEN		8172

extern const unsigned char bounce_sound[8172];

#endif /* __BSOUNDH__ */
