
/**************************************************************
 *	
 *	back, 8 bit, 11025Hz,
 *	1 channel, 701443 bytes/channel
 *	Total Size: 1 * 701443 + 4 (header) = 701487 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Johannes Peltop-Piri\Downloads\back.wav
 *	Time-stamp: Tue Oct 27 01:49:15 2009
 *	
 **************************************************************/

#ifndef __BACKH__
#define __BACKH__

#define GAME_MUSIC_FREQ 11025
#define GAME_MUSIC_LENGTH 701443

extern const unsigned char game_music[701443];

#endif /* __BACKH__ */
